### ISSUE TITLE
重写了description方法后

### ISSUE THREAD

**Issue by mxyolande** [iStarEternal/StarConsoleLink#4]
不知道是哪里出了问题 现在打印出来是这个样子的...
/t好像还可以打印, /n就没反应了 
<CollegeModel: 0x7faef0defd30> {\n    firstLetter = \"C\";\n    name = \"菜单设置\";\n    pinyin = \"hé běi\";\n    province = \"河北\";\n    sid = 2;\n    url = \"cdsz\"\n}",

是不是我插件装多了qvq

**Comment by iStarEternal** [comment]
有截图吗，顺便看下你description是如何重写的

**Comment by mxyolande** [comment]
我使用了YYModel转模型. 后面发现, 有人又拖了一份DDLog进项目....搞了一下事情...
